<?php

$title = 'Maintenance Managment';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->prepare();
echo $this->form($form);
?>
<script>
    function removeConfig(){
        if(confirm('Are you sure to reset maintenance config for default values?')){
            window.location.href = window.location.href + '?drop_db=1';
        }
    }
</script>